spring:
  application:
    name: consumer

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8760/eureka/,http://eureka2:8761/eureka/,http://eureka3:8762/eureka/
    #作为服务消费者，不提供服务，不应该注册自己
    register-with-eureka: false


#负载均衡策略配置 ribbon（默认轮询）
#provider  要配置的负载均衡的服务和@FeignClient相同，否则失效
provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
# 以下配置未测试
    #请求连接超时时间 单位ms
    ConnectTimeout: 5000
    #请求处理的超时时间 单位ms
    ReadTimeout: 5000
    #对所有请求都进行重试
    OkToRetryOnAllOperations: true
    #切换实例的重试次数
    MaxAutoRetriesNextServer: 2
    #对当前实例的重试次数
    MaxAutoRetries: 1

fegin:
  hystrix:
    enabled: true
