spring:
  application:
    name: consumer

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8760/eureka/,http://eureka2:8761/eureka/,http://eureka3:8762/eureka/
    #作为服务消费者，不提供服务，不应该注册自己
    register-with-eureka: false


