spring:
  application:
    name: consumer

server:
  port: 8764

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8760/eureka/,http://eureka2:8761/eureka/,http://eureka3:8762/eureka/


