version: "3.7"
services:
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    image: redis:v1.1
    container_name: redis
    command: ["redis-server", "/usr/local/redis/conf/redis.conf"]
    ports:
      - 6379:6379
    volumes:
      - "/data/redis/conf/redis.conf:/usr/local/redis/conf/redis.conf"
      - "/data/redis/log:/usr/local/redis/log"
      - "/data/redis/data:/data"
    networks:
      app-net:
        ipv4_address: 172.10.10.10
  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    image: eureka:v1.1
    container_name: eureka
    command: ["nohup","java","-Djava.security.egd=file:/dev/./urandom","-jar","/home/app/microservice-eureka.jar",">>","catalina.out","2>&1","&"]
    ports:
      - 8761:8761
    expose:
      - 8761
    volumes:
      - "/data/microservice:/logs"
    networks:
      app-net:
        ipv4_address: 172.10.10.11
    stdin_open: true
    tty: true
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: gateway:v1.1
    container_name: gateway
    command: ["nohup","java","-Djava.security.egd=file:/dev/./urandom","-jar","/home/app/microservice-gateway.jar","--spring.profiles.active=docker",">>","catalina.out","2>&1","&"]
    ports:
      - 8090:8090
    expose:
      - 8090
    volumes:
      - "/data/microservice:/logs"
    networks:
      app-net:
        ipv4_address: 172.10.10.12
    depends_on:
      - redis
      - eureka
    stdin_open: true
    tty: true
  ribbon:
    build:
      context: ./ribbon
      dockerfile: Dockerfile
    image: ribbon:v1.1
    container_name: ribbon
    command: ["nohup","java","-Djava.security.egd=file:/dev/./urandom","-jar","/home/app/microservice-ribbon.jar","--spring.profiles.active=docker",">>","catalina.out","2>&1","&"]
    volumes:
      - "/data/microservice:/logs"
    networks:
      app-net:
        ipv4_address: 172.10.10.13
    depends_on:
      - eureka
    stdin_open: true
    tty: true
networks:
  app-net:
    ipam:
      config:
        - subnet: 172.10.10.0/24
