#模拟集群服务提供者
spring:
  application:
    name: provider

server:
  port: 8764
  #工程名称
#  servlet:
#    context-path: /provider

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8760/eureka/
#      defaultZone: http://eureka1:8760/eureka/,http://eureka2:8761/eureka/,http://eureka3:8762/eureka/
  instance:
    #10秒没有续约，Server会认为改服务宕机，会从服务列表剔除
    lease-expiration-duration-in-seconds: 10
    #服务续约时间单位：秒，默认30秒
    lease-renewal-interval-in-seconds: 5

#日志配置
logging:
  config: classpath:logback-boot.xml
  level:
    com:
      zfw:
        provider:
          conteoller: debug