spring:
  application:
    name: eurekaServer

server:
  port: 8762

eureka:
  client:
    service-url:
      #eureka1 eureka2 对应hosts
      defaultZone: http://eureka1:8760/eureka/,http://eureka2:8761/eureka/
    #单机版为false，关闭自我注册功能，集群需要打开自我注册，所有注册中心相互注册
    register-with-eureka: true
    #默认为true，会从注册中心获取注册信息缓存到本地，以后只会增量获取，可以搭配disable-delta : false来强制每次全部获取
    fetch-registry: true
    #默认开启增量获取更新注册表信息，false则每次会全部获取
#    disable-delta: false
  instance:
    hostname: eureka3
  server:
    enable-self-preservation: false