spring:
  application:
    name: provider

  #jackson
  jackson:
    #为null的属性不参加序列化
    default-property-inclusion: non_null
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 8763
  #工程名称
#  servlet:
#    context-path: /provider

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8760/eureka/,http://eureka2:8761/eureka/,http://eureka3:8762/eureka/
  instance:
    #10秒没有续约，Server会认为改服务宕机，会从服务列表剔除
    lease-expiration-duration-in-seconds: 10
    #服务续约时间单位：秒，默认30秒
    lease-renewal-interval-in-seconds: 5

#日志配置
logging:
  config: classpath:logback-boot.xml
  level:
    com:
      zfw:
        provider:
          conteoller: debug

test:
  name: "lisi"
  path: "www.baidu.com"
  index: 5