spring:
  application:
    name: feign-service
  #链路追踪
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0
  #引入配置
  profiles:
    include: resource

server:
  port: 8767

########-eureka-########
eureka:
  client:
    service-url:
      #单机版
      defaultZone: http://eureka1:8761/eureka/
      #集群模式
#      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
  instance:
    #服务以ip注册
    hostname: 192.168.216.156
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
#    prefer-ip-address: true

########-ribbon-########
#重试：MaxAutoRetries+MaxAutoRetriesNextServer+(MaxAutoRetries * MaxAutoRetriesNextServer) ，即重试3次 （不包括首次调用）一共产生4次调用。
provider-service:
  ribbon:
    #负载均衡策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
    #  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
    #  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
    #  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
    #  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
    #请求连接超时时间 单位ms
    ConnectTimeout: 500
    #请求处理的超时时间 单位ms
    ReadTimeout: 2000
    # 同一实例最大重试次数，不包括首次调用
    MaxAutoRetries: 0
    # 重试其他实例的最大重试次数，不包括首次所选的server
    MaxAutoRetriesNextServer: 2
    # 是否所有操作都进行重试
    #当OkToRetryOnAllOperations设置为false时，只会对get请求进行重试。
    #如果设置为true，便会对所有的请求进行重试，如果是put或post等写操作，
    #如果服务器接口没做幂等性，会产生不好的结果，所以OkToRetryOnAllOperations慎用。
    OkToRetryOnAllOperations: false

########-hystrix-########
#开启断路由
feign:
  hystrix:
    enabled: true

#hystrix超时 > MaxAutoRetries+MaxAutoRetriesNextServer+(MaxAutoRetries * MaxAutoRetriesNextServer) + 1，否则重试没有意义
#-----------------Hystrix配置-----------------------
hystrix:
  # === === === == 默认Command === === === ==
  command:
    default:
      execution:
        isolation:
          # 调用隔离方式, 默认: 采用线程隔离, ExecutionIsolationStrategy:THREAD
          strategy: THREAD
          # 调用超时时间, 默认: 5 秒
          thread:
            timeoutInMilliseconds: 8000
          # 使用信号量隔离时, 命令调用最大的并发数
          semaphore:
            maxConcurrentRequests: 10
      #使用信号量隔离时, 命令fallback调用最大的并发数
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 10
      # === === === == 熔断器 === === === ==
      circuitBreaker:
        # 熔断器在整个统计时间内是否开启的阀值, 默认20个请求
        requestVolumeThreshold: 8
        # 熔断器默认工作时间, 默认: 5 秒
        sleepWindowInMilliseconds: 5
        # 默认: 50%, 当出错率超过50% 后熔断器启动
        errorThresholdPercentage: 50
        # 是否强制开启熔断器阻断所有请求, 默认: false, 不开启
        forceOpen: false
        # 是否允许熔断器忽略错误, 默认false, 不开启
        forceClosed: false
  # === === === == 线程池 === === === ==
  threadpool:
    default:
      # 配置线程池大小, 默认值10个
      coreSize: 10
      # 配置队列长度, 默认-1使用SynchronousQueue,其他值则使用LinkedBlockingQueue:不可动态修改:
      maxQueueSize: -1
      # 队列拒绝的阈值,可通过修改这个变量动态修改允许排队的长度: maxQueueSize=-1时不适用:
      queueSizeRejectionThreshold: 5
      # 线程生存时间, 默认1分钟
      keepAliveTimeMinutes: 1

#
#mybatis-plus:
#  config-location: classpath:/mapper/BayMapper.xml

# 2.0开始，actuator默认不开放，所以要设置为开放
management:
  endpoints:
    web:
      exposure:
        include: "*"  #暴露所有的端点我们可以看到更多应用相关信息
  endpoint:
    health:
      show-details: ALWAYS  #health endpoint是否必须显示全部细节

#日志配置
logging:
  file: ./logs/feign/output.log
  config: classpath:logback-boot.xml
