server:
  port: 34000

spring:
  application:
    name: service1-server
  #sleuth链路追踪
  zipkin:
    base-url: http://127.0.0.1:9411/
  #服务跟踪消息收集率，1代表每一条都收集，0.1代表收集百分之10，如果不配置，有个默认的百分比的
  sleuth:
    sampler:
      probability: 1.0
  #jackson
  jackson:
    #为null的属性不参加序列化
    default-property-inclusion: non_null
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss

eureka:
  client:
    #表示eureka client间隔多久去拉取服务注册信息，默认为30秒，对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
    registry-fetch-interval-seconds: 30
    service-url:
      #单机版 同样适合集群版，但是8761端口挂掉，则新的服务不能再注册
      defaultZone: http://${register.name}:${register.password}@127.0.0.1:31000/eureka/
      #集群版
#      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
  instance:
    #10秒没有续约，Server会认为该服务宕机，会从服务列表剔除
    lease-expiration-duration-in-seconds: 90
    #服务续约时间单位：秒，默认30秒
    lease-renewal-interval-in-seconds: 30
    #服务以ip注册
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

#日志配置
logging:
  config: classpath:logback-boot.xml

register:
  name: zhengll
  password: 123456
