server:
  port: 8090

eureka:
  client:
    service-url:
      #单机版
      defaultZone: http://${register.name}:${register.password}@127.0.0.1:8761/eureka/
      #集群模式
#      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
  instance:
    #服务以ip注册
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}

spring:
  application:
    name: gateway-service
  profiles:
    include: route
  zipkin:
    base-url: http://${host-ip}:9411/
  #服务跟踪消息收集率，1代表每一条都收集，0.1代表收集百分之10，如果不配置，有个默认的百分比的
  sleuth:
    sampler:
      probability: 1.0
  #redis限流
  redis:
    host: 192.168.1.6
    port: 6379
#    host: 192.168.216.198
#    port: 63990
    database: 0
    password: 123456

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

#日志配置
logging:
  config: classpath:logback-boot.xml

register:
  name: zhengll
  password: 123456

host-ip: 192.168.216.103
