eureka:
  client:
    service-url:
      #单机版
      defaultZone: http://${register.name}:${register.password}@172.10.10.11:8761/eureka/
      #集群模式
#      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
  instance:
    #服务以ip注册
    hostname: 172.10.10.12
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}

spring:
  application:
    name: gateway-service
  profiles:
    include: route
  zipkin:
    base-url: http://${host-ip}:9411/
  #服务跟踪消息收集率，1代表每一条都收集，0.1代表收集百分之10，如果不配置，有个默认的百分比的
  sleuth:
    sampler:
      probability: 1.0
  #redis限流
  redis:
    host: 172.10.10.10
    port: 6379
    database: 0

register:
  name: zhengll
  password: 123456

host-ip: 127.0.0.1
