server:
  port: 8090

spring:
  application:
    name: gateway-service
  profiles:
    include: route, hystrix
    active: dev


# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

#日志配置
logging:
  config: classpath:logback-boot.xml

