# hystrix
hystrix:
  command:
    #默认超时配置
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 1000
    #指定服务超时配置
    feignHystrixCommand:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 5000